package view;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Mr.Indian Hacker
 */
public class Retiros extends javax.swing.JFrame {

    private int temp;
    int amount;
    int amount1;

    /**
     * Creates new form WITHDRAW
     */
    public Retiros() {
        initComponents();
    }
    String pass;

    public Retiros(String p) {
        initComponents();
        pass = p;
        setIconImage(new ImageIcon(getClass().getResource("/img/Logo.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lbTitulo1 = new javax.swing.JLabel();
        btRetirar = new javax.swing.JButton();
        txMonto = new javax.swing.JTextField();
        btVolver = new javax.swing.JButton();
        lbTitulo2 = new javax.swing.JLabel();
        lbAdvertencia = new javax.swing.JLabel();
        lbFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lbTitulo1.setFont(new java.awt.Font("Roboto", 1, 26)); // NOI18N
        lbTitulo1.setForeground(new java.awt.Color(4, 89, 160));
        lbTitulo1.setText("Ingrese el monto que desea retirar");

        btRetirar.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        btRetirar.setForeground(new java.awt.Color(240, 240, 240));
        btRetirar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1.png"))); // NOI18N
        btRetirar.setText("Retirar");
        btRetirar.setBorderPainted(false);
        btRetirar.setContentAreaFilled(false);
        btRetirar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btRetirar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2.png"))); // NOI18N
        btRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRetirarActionPerformed(evt);
            }
        });

        txMonto.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        txMonto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txMonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txMontoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txMontoKeyTyped(evt);
            }
        });

        btVolver.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        btVolver.setForeground(new java.awt.Color(255, 255, 255));
        btVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/3.png"))); // NOI18N
        btVolver.setText("Volver");
        btVolver.setBorderPainted(false);
        btVolver.setContentAreaFilled(false);
        btVolver.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btVolver.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/4.png"))); // NOI18N
        btVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVolverActionPerformed(evt);
            }
        });

        lbTitulo2.setFont(new java.awt.Font("Roboto", 1, 26)); // NOI18N
        lbTitulo2.setForeground(new java.awt.Color(4, 89, 160));
        lbTitulo2.setText("Presione \"Retirar\"");

        lbAdvertencia.setFont(new java.awt.Font("Roboto", 0, 25)); // NOI18N
        lbAdvertencia.setForeground(new java.awt.Color(255, 0, 0));
        lbAdvertencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAdvertencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbFondo.setFont(new java.awt.Font("Roboto", 1, 26)); // NOI18N
        lbFondo.setForeground(new java.awt.Color(4, 89, 160));
        lbFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/5.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(lbTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(txMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(540, 540, 540)
                .addComponent(btRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addComponent(lbTitulo2))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(btVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lbFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(lbAdvertencia, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(lbTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(txMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(lbAdvertencia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(270, 270, 270)
                .addComponent(btRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(440, 440, 440)
                .addComponent(lbTitulo2))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(700, 700, 700)
                .addComponent(btVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lbFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRetirarActionPerformed

        amount = (Integer.parseInt(txMonto.getText()));

        if (amount > 2500000) {
            lbAdvertencia.setText("No puedes retirar mas de 2.500.000");
            volver1();
        } else if (amount % 50000 != 0 && amount % 20000 != 0) {
            lbAdvertencia.setText("No puede retirar");
            volver1();

        } else {

            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/atm2", "root", "2018");
                Statement stmt = null;
                ResultSet rs = null;

                String SQL = "SELECT * FROM details WHERE password like '%" + (pass) + "%'";

                stmt = con.createStatement();
                rs = stmt.executeQuery(SQL);

                if (rs.next() != rs.isAfterLast()) {
                    String cuser = rs.getString("username");
                    String cpass = rs.getString("password");
                    int cbal = Integer.parseInt(rs.getString("balance"));
                    if (cbal >= amount) {

                        amount1 = amount * 4 / 1000;
                        setTemp((cbal - amount) - amount1);

                        System.out.println(getTemp());
                        //System.out.println(amount);

                        String SQL1 = "SELECT * FROM details";
                        stmt = con.createStatement();
                        rs = stmt.executeQuery(SQL1);

                        String strSQL = "Update details set balance = " + (getTemp()) + " where password = " + (pass);
                        int rowsEffected = stmt.executeUpdate(strSQL);
                        if (rowsEffected == 0) {
                            System.out.println("No se realizo el retiro");
                        } else {
                            Recibo oRecibo = new Recibo(pass);
                            oRecibo.setVisible(true);
                            Recibo.lbRetiro.setText("$ " + txMonto.getText());
                            Recibo.lbUsuario.setText(cuser);
                            Recibo.lbSaldo.setText(String.valueOf(getTemp()));
                            Recibo.lbCosto.setText(String.valueOf(amount1));
                            Fecha();

                            dispose();
                        }
                    } else {
                        lbAdvertencia.setText("No tiene suficiente dinero");
                        volver1();
                    }
                    con.close();
                    stmt.close();
                    rs.close();
                }
            } catch (HeadlessException | ClassNotFoundException | NumberFormatException | SQLException e) {
                System.out.println("Error" + e.getMessage());
            }
        }
    }//GEN-LAST:event_btRetirarActionPerformed

    private void btVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVolverActionPerformed
        int amount1;
        int temp;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/atm2", "root", "2018");
            Statement stmt = null;
            ResultSet rs = null;

            String SQL = "SELECT * FROM details WHERE password like '%" + (pass) + "%'";

            stmt = con.createStatement();
            rs = stmt.executeQuery(SQL);

            if (rs.next() != rs.isAfterLast()) {
                String cuser = rs.getString("username");
                String cpass = rs.getString("password");
                int cbal = Integer.parseInt(rs.getString("balance"));
                if (cbal >= 0) {

                    amount1 = 0 * 4 / 1000;
                    temp = ((cbal - 0) - amount1);

                    //System.out.println(temp);
                    //System.out.println(amount);
                    String SQL1 = "SELECT * FROM details";
                    stmt = con.createStatement();
                    rs = stmt.executeQuery(SQL1);

                    String strSQL = "Update details set balance = " + (temp) + " where password = " + (pass);
                    int rowsEffected = stmt.executeUpdate(strSQL);
                    if (rowsEffected == 0) {
                        System.out.println("No se realizo el retiro");
                    } else {
                        Inicio oInicio = new Inicio(pass);
                        oInicio.setVisible(true);
                        Inicio.lbUsuario.setText(cuser);
                        dispose();
                    }
                } else {
                    //lbAdvertencia.setText("No tiene suficiente dinero");
                    //limpiar();
                }
                con.close();
                stmt.close();
                rs.close();
            }
        } catch (HeadlessException | ClassNotFoundException | NumberFormatException | SQLException e) {
            System.out.println("Error" + e.getMessage());
        }
    }//GEN-LAST:event_btVolverActionPerformed
    private void limpiar() {
        txMonto.setText("");
    }

    private void volver1() {
        new Thread() {
            @Override
            public void run() {
                try {
                    Thread.sleep(2000);
                    lbAdvertencia.setText("");
                    limpiar();
                } catch (InterruptedException ex) {
                    System.out.println(ex.getMessage());
                }
            }
        }.start();
    }
    private void txMontoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txMontoKeyReleased
        if (txMonto.getText().length() > 0) {
            if (Integer.parseInt(txMonto.getText()) % 50000 != 0 && Integer.parseInt(txMonto.getText()) % 20000 != 0) {
                lbAdvertencia.setText("Solo puedes retirar multiplos de 50.000 o de 20.000");
            } else {
                lbAdvertencia.setText("");
            }
        }
    }//GEN-LAST:event_txMontoKeyReleased

    private void txMontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txMontoKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txMontoKeyTyped

    public void Fecha() {
        Calendar fecha = new GregorianCalendar();
        String anio = Integer.toString(fecha.get(Calendar.YEAR));
        String mes = Integer.toString(fecha.get(Calendar.MONTH) + 1);
        String dia = Integer.toString(fecha.get(Calendar.DATE));
        String fechaFin = dia + "/" + mes + "/" + anio;

        String hora = Integer.toString(fecha.get(Calendar.HOUR_OF_DAY));
        String minuto = Integer.toString(fecha.get(Calendar.MINUTE));
        String horaFin = hora + ":" + minuto;

        Recibo.lbFecha.setText(fechaFin + " -- " + horaFin);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Retiros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Retiros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Retiros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Retiros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Retiros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRetirar;
    private javax.swing.JButton btVolver;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbAdvertencia;
    private javax.swing.JLabel lbFondo;
    private javax.swing.JLabel lbTitulo1;
    private javax.swing.JLabel lbTitulo2;
    private javax.swing.JTextField txMonto;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the temp
     */
    public int getTemp() {
        return temp;
    }

    /**
     * @param temp the temp to set
     */
    public void setTemp(int temp) {
        this.temp = temp;
    }
}
